#
# @Cache-Control: 
# @infer true
# @view 
#
#
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>

SELECT ?resource ?label  
{
    ?resource foaf:name ?label .
    ?resource a foaf:Person . 
    
        	
    FILTER (regex(str(?resource), "", "i") &&
            (lang(?label) = '' || lang(?label) = 'pt' || lang(?label) = 'en') && 
            regex(str(?label), "$keyword", "i")) .

} 
ORDER BY ?label
