#
# @Cache-Control: 
# @infer true
# @view 
#
#
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
PREFIX ssn-system:<http://www.w3.org/ns/ssn/systems/>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX sosa:<http://www.w3.org/ns/sosa/>
PREFIX ssn: <http://www.w3.org/ns/ssn/>
PREFIX calliSensorModel: <http://localhost:8080/app-sensor-catalog/Actuator-Model/>

SELECT ?resource ?label  
{
    ?resource rdfs:label ?label .
    ?resource a owl:Class .
    ?resource rdfs:subClassOf sosa:Actuator .  
    ?resource rdfs:subClassOf ssn:System .
    ?resource a calliSensorModel:ActuatorModel .
    
 


} 
ORDER BY ?label
